#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0+
# License-Filename: LICENSES/GPL-3.0

import gi
gi.require_version("GLib", "2.0")

from gi.repository import Gio, GLib

# declared in gnome-session/gsm-inhibitor-flag.h
GSM_INHIBITOR_FLAG_SUSPEND = 4;

def on_activate(app):
    if app._inhibitor:
        return

    app.hold()

    # Inhibit logind's lid switch handling
    bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
    var, fdlist = bus.call_with_unix_fd_list_sync('org.freedesktop.login1',
                                                  '/org/freedesktop/login1',
                                                  'org.freedesktop.login1.Manager',
                                                  'Inhibit',
                                                  GLib.Variant('(ssss)',
                                                               ('handle-lid-switch',
                                                                'gnome-tweaks',
                                                                'user preference',
                                                                'block')),
                                                  None, 0, -1, None, None)
    app._inhibitor = Gio.UnixInputStream(fd=fdlist.steal_fds()[var[0]])

    # Inhibit gnome-session's suspend handling
    bus_session = Gio.bus_get_sync(Gio.BusType.SESSION, None)
    bus_session.call_with_unix_fd_list_sync('org.gnome.SessionManager',
                                            '/org/gnome/SessionManager',
                                            'org.gnome.SessionManager',
                                            'Inhibit',
                                            GLib.Variant('(susu)',
                                                         ('gnome-tweaks',
                                                         0,
                                                        'user preference',
                                                         GSM_INHIBITOR_FLAG_SUSPEND)),
                                            None, 0, -1, None, None)


def on_quit_action(action, param, app):
    app.quit()

if __name__ == '__main__':
    app = Gio.Application(application_id='org.gnome.tweak-tool.lid-inhibitor', flags=0)
    app.connect('activate', on_activate)
    app._inhibitor = None

    action = Gio.SimpleAction(name='quit')
    app.add_action(action)
    action.connect('activate', on_quit_action, app)

    app.run([])
