#!/usr/bin/env python

import os.path
import optparse

from gi.repository import Gtk

import gtweak
from gtweak.tweakmodel import TweakModel
from gtweak.tweakview import TweakView

class MainWindow:
    def __init__(self):
        builder = Gtk.Builder()

        assert(os.path.exists(gtweak.DATA_DIR))

        filename = os.path.join(gtweak.DATA_DIR, 'shell.ui')
        builder.add_from_file(filename)
        
        welcome = builder.get_object('welcome_image')
        welcome.set_from_file(os.path.join(gtweak.DATA_DIR, 'welcome.png'))
        
        notebook = builder.get_object('notebook')
        entry = builder.get_object('search_entry')
        tweak_box = builder.get_object('tweak_vbox')
        model = TweakModel()
        view = TweakView(
                    notebook,
                    entry,
                    tweak_box,
                    model)
        builder.get_object('overview_sw').add(view.treeview)

        window = builder.get_object('main_window')
        window.set_size_request(640, 480)
        window.connect('destroy', Gtk.main_quit)
        window.show_all()
        
    def run(self):
        Gtk.main()

if __name__ == '__main__':
    parser = optparse.OptionParser()
    parser.add_option("-t", "--test", action="store_true",
                  help="Enable test code")
    parser.add_option("-s", "--schema-dir",
                  help="GSesettings schema dir", metavar="FILE")
    options, args = parser.parse_args()

    try:
        from gtweak.defs import GSETTINGS_SCHEMA_DIR, TWEAK_DIR, DATA_DIR
    except ImportError:
        GSETTINGS_SCHEMA_DIR = "/usr/share/glib-2.0/schemas/"
        _me = os.path.abspath(os.path.dirname(__file__))
        TWEAK_DIR = os.path.join(_me, "gtweak", "tweaks")
        DATA_DIR = os.path.join(_me, "data")

    gtweak.GSETTINGS_SCHEMA_DIR = options.schema_dir or GSETTINGS_SCHEMA_DIR
    gtweak.TWEAK_DIR = TWEAK_DIR
    gtweak.DATA_DIR = DATA_DIR
    gtweak.ENABLE_TEST = options.test

    MainWindow().run()

